var mongoose = require('libs/mongoose');
var Schema = mongoose.Schema;

var schema = new Schema({
    external_system : String,
    adv_campaign_id : String,
    advertiser : String,
    title : String,
    app_description : String,
    import_data : String,
    end_date : Boolean,
    timezone : String,
    daily_cap : Number,
    cap_limitation : Number,
    traffic_sources_and_restrictions : Object,
    status : Number,
    convertion_modes : String,
    attribution_window : String,
    cr_blocking_value : String,
    cr_low_limit : String,
    direct_campaign : Boolean,
    adv_campaign_api : String,
    payouts : Array,
    app_url : String,
    tracking_url_parameters : String,
    app_id : String,
    app_categories : Array,
    app_size : String,
    app_main_logo : String,
    app_images : Array,
    playmarket_app_id : String,
    rating_android : String,
    kids_safe : String,
    kpi_interval : Number,
    created_at : Number,
    events_received : Boolean,
    updated_at : Number,
    is_daily_capped : Boolean,
    title_sub_title : String,
    readable_id : Number,
    creatives_id : String,
    sub_title : String,
    app_url_2 : String,
    itunes_app_id : String,
    tracking_url_ios : String,
    tracking_url_ipad : String,
    tracking_url_wp : String,
    app_developer : String,
    rating_ios : String,
    convertion_modes_details : String,
    start_date : Boolean,
    ignore_import : String,
    cr_blocking_value_low : String,
    cr_low_limit_low : String,
    targeting_tips : String,
    notes : Object,
    exclusive_publishers : Array,
    last_status_change : Number,
    payable_event : Boolean
});

module.exports = mongoose.model('Campaign', schema, 'campaigns');